### ISSUE TITLE
[FE] 피그마 : 메인 페이지 제작

### ISSUE THREAD

**Issue by Jeong-hae-rim** [kdh-92/Tiggle#43]
### TODO
- **컴포넌트**
  - 거래 cell 디자인
    - [x] 타입 별 디자인 (지출 / 수입 / 환불)
    - [ ] 반응형 별 디자인 (모바일 / 타블렛 / 데스크탑)
- **화면**
  - [x] 모바일 화면 제작 (375 ~ 767)
  - [ ] 타블렛 화면 제작 (768 ~ 1279)
  - [ ] 데스크탑 화면 제작 (1280 ~ )
